apiVersion: v1
kind: ConfigMap
metadata:
  name: user-bff-configmap
  namespace: dev
data:
  NODE_ENV: development
  PORT: '4000'
  BE_HTTP_URL: 'http://user-be-svc.dev.svc.cluster.local:5001'
  BE_GRPC_URL: 'user-be-svc.dev.svc.cluster.local:5000'
  GRAPHQL_PLAYGROUND_ENABLED: 'false'
  JWT_SECRET: 'zaqwsxcdeRFVvFrTgb'
  REDIS_HOST: 'redis-external'
  REDIS_PORT: '6379'
  REDIS_PASS: 'redis123'
  REDIS_DB: '0'
  REDIS_KEY_PREFIX: 'user_bff_socket_service:'
  REDIS_QUEUE_PREFIX: 'user_queue:'
