apiVersion: v1
kind: ConfigMap
metadata:
  name: user-bff-configmap
  namespace: dev
data:
  NODE_ENV: development
  PORT: '4000'
  BE_HTTP_URL: 'http://user-be-svc.user-be-dev.svc.cluster.local:5001'
  BE_GRPC_URL: 'user-be-svc.user-be-dev.svc.cluster.local:5000'
