apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev

resources:
  - ./../../base
  # - secrets.yaml
  - configmap.yaml

# If you have any patches to apply to the base resources, you can specify them here.
# patches:
#   - path: deployment-patch.yml
#     target:
#       kind: Deployment

images:
  - name: deployment-image
    newName: quangmanhlam/user-bff-dev
    newTag: b8ee59d30694f7f755d998602e4ebee8e2651903
