# Kustomization Document : https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml
  - hpa.yaml
  - postgres-external-service.yml
  - redis-external-service.yml
