apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: user-fe-ingress
  namespace: dev
spec:
  entryPoints:
    - web
    - websecure
  routes:
    # Route cho GraphQL API - set before PathPrefix has priority higher than catch all
    - match: Host(`demo-dev.manhlam.name.vn`) && PathPrefix(`/graphql`)
      kind: Rule
      services:
        - name: user-bff-svc
          port: 4000
    # Route cho frontend - catch all
    - match: Host(`demo-dev.manhlam.name.vn`)
      kind: Rule
      services:
        - name: user-fe-svc
          port: 3000
