apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: user-fe-ingress
  namespace: dev
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`demo-dev.manhlam.name.vn`)
      kind: Rule
      services:
        - name: user-fe-svc
          port: 3000
  # Nếu dùng Cloudflare SSL, không cần tls section
  # Nếu cần Let's Encrypt, uncomment và config certResolver
  # tls:
  #   certResolver: letsencrypt
