apiVersion: v1
kind: ConfigMap
metadata:
  name: user-be-configmap
  namespace: dev
data:
  NODE_ENV: development
  HTTP_HOST: '0.0.0.0'
  PORT: '5001'
  GRPC_HOST: '0.0.0.0'
  GRPC_PORT: '5000'
  DB_HOST: postgres-external
  DB_PORT: '5432'
  DB_USER: postgres
  DB_PASS: postgres
  DB_NAME: user
  JWT_SECRET: zaqwsxcdeRFVvFrTgb
  JWT_EXPIRATION: '86400'
  REDIS_HOST: redis-external
  REDIS_PORT: '6379'
  REDIS_PASS: 'redis123'
